name: Build ObjViewer Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.11.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw53'

    - name: Configure project with qmake
      run: |
        cd ObjViewer
        mkdir build
        cd build
        qmake ../ObjViewer.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" 

    - name: Build project
      run: |
        echo "${{ env.QT_ROOT_DIR }}/bin" >> $GITHUB_PATH
        echo $GITHUB_PATH
        cd ObjViewer/build
        mingw32-make debug

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-debug
        path: ObjViewer/build-debug/
