name: Build ObjViewer Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Install Qt
    #  uses: jurplel/install-qt-action@v4
    #  with:
    #    version: '5.11.3'
    #    host: 'windows'
    #    target: 'desktop'
    #    arch: 'win32_mingw53'

    - name: Install Qt and MinGW
      run: |
        cd D:\a\OBJViewer\OBJViewer
        curl -L -o qt-installer.exe https://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
        cd D:\a\OBJViewer\OBJViewer
        start "qt-installer.exe --silent --no-qt-plugins --platform minimal" /wait 

        cd D:\a\OBJViewer\OBJViewer
        curl -L -o mingw-installer.exe https://sourceforge.net/projects/mingw-w64/files/latest/download
        cd D:\a\OBJViewer\OBJViewer
        start "mingw-installer.exe /S" /wait

    - name: Configure project with qmake
      run: |
        cd ObjViewer
        mkdir build
        cd build
        qmake ../ObjViewer.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" 

    - name: Build project
      run: |
        echo "${{ env.QT_ROOT_DIR }}\\bin" >> $GITHUB_PATH
        cd ObjViewer/build
        mingw32-make debug

    #- name: Archive build artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: build-debug
    #    path: ObjViewer/build-debug/
