name: Build ObjViewer Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build-type: [debug, release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.11.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win32_mingw73'

    - name: Configure project with qmake
      run: |
        cd ObjViewer
        mkdir build-${{ matrix.build-type }}
        cd build-${{ matrix.build-type }}
        qmake CONFIG+=${{ matrix.build-type }} ../ObjViewer.pro

    - name: Build project
      run: |
        cd ObjViewer/build-${{ matrix.build-type }}
        mingw32-make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.build-type }}
        path: ObjViewer/build-${{ matrix.build-type }}/
